export type Role = "OWNER" | "ADMIN" | "DOCTOR" | "RECEPTION";

export type Permission =
  | "TUTOR_READ"
  | "TUTOR_CREATE"
  | "PET_READ"
  | "PET_CREATE"
  | "APPOINTMENT_READ"
  | "APPOINTMENT_CREATE"
  | "APPOINTMENT_UPDATE"
  | "APPOINTMENT_DELETE";

export const rolePermissions: Record<Role, Permission[]> = {
  OWNER: [
    "TUTOR_READ", "TUTOR_CREATE",
    "PET_READ", "PET_CREATE",
    "APPOINTMENT_READ", "APPOINTMENT_CREATE", "APPOINTMENT_UPDATE", "APPOINTMENT_DELETE",
  ],
  ADMIN: [
    "TUTOR_READ", "TUTOR_CREATE",
    "PET_READ", "PET_CREATE",
    "APPOINTMENT_READ", "APPOINTMENT_CREATE", "APPOINTMENT_UPDATE", "APPOINTMENT_DELETE",
  ],
  DOCTOR: [
    "TUTOR_READ",
    "PET_READ",
    "APPOINTMENT_READ",
    "APPOINTMENT_UPDATE",
  ],
  RECEPTION: [
    "TUTOR_READ", "TUTOR_CREATE",
    "PET_READ", "PET_CREATE",
    "APPOINTMENT_READ", "APPOINTMENT_CREATE", "APPOINTMENT_UPDATE",
  ],
};
